### PR TITLE
Fix #1 and #2

### LINKED ISSUE #1: Local random source being tainted with non-random values
At line [60](https://github.com/RandomSanityProject/randomsanity_debian/blob/master/randomsanity#L60), the whole response, which contain non-random values, is written to `/dev/urandom`.

Also, another bug prevents getting the response correctly (see issue #2 ).

An example response is the following:

```
HTTP/1.1 200 OK
Content-Type: application/json
X-Entropy: 89f4f79ca1c0079d6f6324ead4ff522939a425bb232c8fdfdd1b8f7447a71d83
X-Cloud-Trace-Context: 408cbcabc537219ef96f45393b4cd527;o=1
Date: Tue, 02 May 2017 12:10:50 GMT
Server: Google Frontend
Content-Length: 4

true
```

Only `X-Entropy` should be used, not the entire response. I might submit a patch for this.

### PR DESCRIPTION
**Pull request by HacKanCuBa**

### CODE REVIEW

**Comment by gavinandresen** [comment]
Awesome thanks!

If you have more fixes, they'll go a little smoother if you fix one issue per pull request and refer to the issue in the pull request description (github will automagically close the issue for me when pulled).

**Comment by HacKanCuBa** [comment]
Both commits individually close those issues. In the issue log, there's a pointer to the reference.
Can I split this PR in one per commit? Do you want me to try that?

**Comment by HacKanCuBa** [comment]
I'm trying to split this PR, but it's not letting me, probably because this one is open. So I'm closing this.

**Comment by HacKanCuBa** [comment]
I can't make a PR for the first commit alone, Github isn't letting me. I believe the issues will close automatically when merged, given that the commits have the appropriate wording.

**Pull request merged**
